"""Pydantic schemas for the execution plan generated by the router."""

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field


class ExecutionStep(BaseModel):
    step_id: str
    tool: str
    depends_on: list[str] = Field(default_factory=list)
    resource_lane: str = "cpu"
    params: dict[str, Any] = Field(default_factory=dict)


class ParallelGroup(BaseModel):
    group_id: str
    can_run_parallel: bool = True
    steps: list[ExecutionStep] = Field(default_factory=list)


class SkippedTool(BaseModel):
    tool: str
    reason: str


class ExecutionPlan(BaseModel):
    workflow: str
    intent: str = ""
    requires_visual_output: bool = True
    parallel_groups: list[ParallelGroup] = Field(default_factory=list)
    skipped_tools: list[SkippedTool] = Field(default_factory=list)

    def all_steps(self) -> list[ExecutionStep]:
        steps = []
        for group in self.parallel_groups:
            steps.extend(group.steps)
        return steps

    def all_step_ids(self) -> set[str]:
        return {step.step_id for step in self.all_steps()}

    def flat_parallel_groups(self) -> list[list[str]]:
        return [[step.tool for step in group.steps] for group in self.parallel_groups]
